# Generated by Django 3.1.2 on 2021-04-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_education_positions_speaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='speaker',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
